### ISSUE TITLE
apiHelper.py content not content() and sys.exit only accepts 1 (str) argument

### ISSUE THREAD

**Issue by berndtlindner** [Icepack-co/examples#3]
I tried running code on google colab and noticed there was bug in [apiHelper.py](https://github.com/Icepack-co/examples/blob/master/python/apiHelper.py)

I have fixed this on a local branch and can push up and created merge request if you would like (just need perms), but below is the code change.

![image](https://user-images.githubusercontent.com/10104751/104838136-a2e85680-58c1-11eb-9597-e1503c105dfb.png)

**Comment by TheCoolRob** [comment]
Thanks @berndtlindner - feel free to throw that change in a PR and we'll pull it throuhg to the master branch :+1:

**Comment by berndtlindner** [comment]
Cool @TheCoolRob , I just need permissions to do that.
